### ISSUE TITLE
`deferred` compatibility with `dev_appserver`

### ISSUE THREAD

**Issue by phil-lopreiato** [GoogleCloudPlatform/appengine-python-standard#45]
I think https://github.com/GoogleCloudPlatform/appengine-python-standard/issues/31 and https://github.com/GoogleCloudPlatform/appengine-python-standard/pull/42 may not go far enough.

I encountered an issue with a similar trace to the above, even after making sure `DEFERRED_USE_CROSS_COMPATIBLE_PICKLE_PROTOCOL` was set:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/api/taskqueue/taskqueue_stub.py", line 2192, in MainLoop
    self._ProcessQueues()
  File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/api/taskqueue/taskqueue_stub.py", line 2137, in _ProcessQueues
    response_code = self.task_executor.ExecuteTask(task, queue)
  File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/api/taskqueue/taskqueue_stub.py", line 2069, in ExecuteTask
    '0.1.0.2')
  File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/dispatcher.py", line 803, in add_request
    fake_login=fake_login)
  File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/module.py", line 1250, in build_request_environ
    'wsgi.input': six.StringIO(six.ensure_text(body))
  File "/usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/_internal/six/__init__.py", line 952, in ensure_text
    return s.decode(encoding, errors)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc0 in position 529: invalid start byte
```

### What `dev_appserver` does

The `taskqueue` stub has to re-marshall the payload back as an HTTP request to the local server, which then can un-pickle and process it. Here's the code (which remember, is running in python2 still)

```python
# From /usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/module.py
  def build_request_environ(self,
                            method,
                            relative_url,
                            headers,
                            body,
                            source_ip,
                            port,
                            fake_login=False):
    logging.warning("task body: {}".format(body))
    if isinstance(body, six.text_type):
      body = body.encode('ascii')

    url = six.moves.urllib.parse.urlsplit(relative_url)
    if port != 80:
      if ':' in self.host:
        host = '[%s]:%s' % (self.host, port)
      else:
        host = '%s:%s' % (self.host, port)
    else:
      host = self.host
    import base64
    environ = {
        constants.FAKE_IS_ADMIN_HEADER: '1',
        'CONTENT_LENGTH': str(len(body)),
        'PATH_INFO': url.path,
        'QUERY_STRING': url.query,
        'REQUEST_METHOD': method,
        'REMOTE_ADDR': source_ip,
        'SERVER_NAME': self.host,
        'SERVER_PORT': str(port),
        'SERVER_PROTOCOL': 'HTTP/1.1',
        'wsgi.version': (1, 0),
        'wsgi.url_scheme': 'http',
        'wsgi.errors': six.StringIO(),
        'wsgi.multithread': True,
        'wsgi.multiprocess': True,
        'wsgi.input': six.StringIO(six.ensure_text(body))
    }
    if fake_login:
      environ[constants.FAKE_LOGGED_IN_HEADER] = '1'
    util.put_headers_in_environ(headers, environ)
    environ['HTTP_HOST'] = host
    return environ
```

#### Why this can fail

Even when using pickle protocol zero, which `DEFERRED_USE_CROSS_COMPATIBLE_PICKLE_PROTOCOL`, the serialized contents can still contain non-utf characters

### Example

Pickle protocol 0 doesn't actually guarantee to be 100% ascii characters, see https://bugs.python.org/issue38241

The easiest example is if an argument to the deferred function contains an `ndb.Model` instance with a `ndb.StructuredProperty` (who ends up getting serialized as a protobuf encoding, containing characters outside the unicode range). Even without the validation, this will run into trouble due to valid character ranges for http requests.

```
Python 3.10.0 (default, Oct  4 2021, 00:00:00) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.appengine.ext import ndb
>>> import pickle
>>> 
>>> class SubModel(ndb.Model):
...     prop = ndb.StringProperty()
... 
>>> class TestModel(ndb.Model):
...     sub_prop = ndb.StructuredProperty(SubModel)
... 
>>> m = TestModel(sub_prop=SubModel(prop="test"))
>>> pickled = pickle.dumps(m, 0)
>>> 
>>> import six
>>> six.ensure_text(pickled)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/phil/Documents/tba/the-blue-alliance-py3/venv/lib/python3.10/site-packages/six.py", line 951, in ensure_text
    return s.decode(encoding, errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 181: invalid start byte
```

### A Better Solution?

Instead of using protocol 0, I think we can instead use any python2-compatible protocol, but also base64 encode the pickled data so w can be absolutely sure the characters we pass on the wire are within the expected range.

This would break cases where code running this library enqueues a deferred task to run against the legacy builtin version, so this may not be fully acceptable?

Also, I can't fully figure out why the example in my app didn't run into this problem when running entirely under python2, the best I can figure is that the legacy runtime [didn't perform that validation](https://github.com/GoogleCloudPlatform/python-compat-runtime/blob/master/appengine-compat/exported_appengine_sdk/google/appengine/tools/devappserver2/module.py#L1118-L1150) and without the python3 `str`/`bytes` differences in the mix, this may have just never come up?

**Comment by shreejad** [comment]
hey @phil-lopreiato, can you share the callable from your app that you are deferring? I can reproduce the utf error in a Python3 environment, but when I wrap the same (`m = TestModel(sub_prop=SubModel(prop="test"))`) in a function, the error does not occur. I'm guessing this might be because only the function name might be getting pickled, not sure.

Having the exact code snippet that triggers this bug would be helpful!

**Comment by phongthanfz** [comment]
I clone code from https://cloud.google.com/appengine/docs/standard/python3/services/deferred#django  and run it with dev_appserver.py, when i call deferred function, it always has errors and don't know how to debug
```
ERROR    2022-06-09 16:41:06,683 module.py:1008] Request to u'/_ah/queue/deferred' failed
INFO     2022-06-09 16:41:06,683 module.py:890] default: "POST /_ah/queue/deferred HTTP/1.1" 500
```
i use version `appengine-python-standard==1.0.0`

**Comment by fpwill** [comment]
@phongthanfz I've patched my Python 2 app by replacing deferred.serialize when running on the dev_appserver. The only real change is "protocol=0" vs "protocol=pickle.HIGHEST_PROTOCOL" in the real implemention.

Below is the GIST of it - allows me to work somewhat normally on the dev server. I recognize that protocol=0 my not work across the board - as mentioned in comments above. But this swap really helped me keep plugging away. You could add something like this to your "appengine_config.py" file at the root of your default/python2 service.
`    
if os.environ.get('SERVER_SOFTWARE', '').startswith('Dev'):

    import pickle
    from google.appengine.ext.deferred import deferred

    def _deferred_serialize(obj, *args, **kwargs):
        curried = deferred._curry_callable(obj, *args, **kwargs)
        return pickle.dumps(curried, protocol=0)

    deferred.serialize = _deferred_serialize
`

**Comment by phongthanfz** [comment]
@fpwill thank you so much, it worked for me.

**Comment by phil-lopreiato** [comment]
I think this may have actually been fixed in a newer version of the SDK. I can't find this mentioned in a changelog anywhere, nor can I find a source mirror to easily validate, but from a quick bisect locally with the releases, the line in question seems to have changed starting with version 380.0.0 (released 2022-04-05).

Now, the text coercion doesn't seem to be present anymore and it uses `BytesIO` instead (which is more correct, I think).

So, I think I can close this issue, although if anyone else encounters

```python
# now, from /usr/lib/google-cloud-sdk/platform/google_appengine/google/appengine/tools/devappserver2/module.py
# compare this to the version in the OP
 def build_request_environ(self,
                            method,
                            relative_url,
                            headers,
                            body,
                            source_ip,
                            port,
                            fake_login=False):
    if isinstance(body, six.text_type):
      body = body.encode('ascii')

    url = six.moves.urllib.parse.urlsplit(relative_url)
    if port != 80:
      if ':' in self.host:
        host = '[%s]:%s' % (self.host, port)
      else:
        host = '%s:%s' % (self.host, port)
    else:
      host = self.host
    environ = {
        constants.FAKE_IS_ADMIN_HEADER: '1',
        'CONTENT_LENGTH': str(len(body)),
        'PATH_INFO': url.path,
        'QUERY_STRING': url.query,
        'REQUEST_METHOD': method,
        'REMOTE_ADDR': source_ip,
        'SERVER_NAME': self.host,
        'SERVER_PORT': str(port),
        'SERVER_PROTOCOL': 'HTTP/1.1',
        'wsgi.version': (1, 0),
        'wsgi.url_scheme': 'http',
        'wsgi.errors': six.StringIO(),
        'wsgi.multithread': True,
        'wsgi.multiprocess': True,
        'wsgi.input': six.BytesIO(body)
    }
    if fake_login:
      environ[constants.FAKE_LOGGED_IN_HEADER] = '1'
    util.put_headers_in_environ(headers, environ)
    environ['HTTP_HOST'] = host
    return environ
```

**Comment by ubragg** [comment]
Will these changes ever be propagated to the libraries that come with the GoogleCloudSDK?  There it still appears that the patch suggested by @fpwill is necessary to run python2 apps that use the deferred library.

**Comment by fpwill** [comment]
> 

@ubragg I haven't retested my app with the newer versions of the SDK that @phil-lopreiato mentioned. If they fixed the offending code:
`'wsgi.input': six.StringIO(six.ensure_text(body))`

Then there is a good chance that my dev_server patch is unnecessary. However the env_variables below may still be necessary if your app is passing any of these elements between python2 and python3 services. I'm mostly concerned with the deferred stuff and I've made an alternative endpoint for one of the service so that it doesn't cross over.

```
env_variables:
  NDB_USE_CROSS_COMPATIBLE_PICKLE_PROTOCOL: True
  MEMCACHE_USE_CROSS_COMPATIBLE_PROTOCOL: True
  DEFERRED_USE_CROSS_COMPATIBLE_PICKLE_PROTOCOL:  True
```

**Comment by ubragg** [comment]
@fpwill Yeah, I tested with the latest version of the SDK without the patch, and it didn't work.  Also, the change that utilizes `DEFERRED_USE_CROSS_COMPATIBLE_PICKLE_PROTOCOL` to essentially do what the patch is doing isn't merged in there yet. I'm just wondering if there is a plan for it to eventually be updated.

**Comment by vbraun** [comment]
Issue corresponds to this google issue tracker entry: https://issuetracker.google.com/issues/219885365
